package com.benzrf.toomanyplants;

import net.minecraft.server.Block;
import net.minecraft.server.Item;

public class TMPObjectsDeclaration
{
    int glowTexture;
    int preGlowFlowerId;
    public Block blockpreglowflower;
    int glowFlowerId;
    public Block blockglowflower;
    int evilFlowerTexture;
    int evilFlowerId;
    public Block blockevilflower;
    int evilFlowerPetalTexture;
    int evilFlowerPetalId;
    public Item itemevilflowerpetal;
    int animationEssenceTexture;
    int animationEssenceId;
    public Item itemanimationessence;
    int airFlowerTexture;
    int airFlowerId;
    public Block blockairflower;
    int rainstickTexture;
    int rainstickId;
    public Item itemrainstick;
    int beanstalkTexture;
    int beanstalkId;
    public Block blockbeanstalk;
    int magicBeanTexture;
    int magicBeanId;
    public Item itemmagicbean;
    int lesserMagicBeanTexture = 8;
    int lesserMagicBeanId;
    public Item itemlessermagicbean;
    int podTexture;
    int podId;
    public Block blockpod;
    int beanPlantTexture;
    int beanPlantId;
    public Block blockbeanplant;
    int beanSproutTexture;
    int beanSproutId;
    public Block blockbeansprout;
    int beanTexture;
    int beanId;
    public Item itembean;
    int beanStewTexture;
    int beanStewId;
    public Item itembeanstew;
    int pitcherPlantTexture;
    int pitcherPlantId;
    public Block blockpitcherplant;
    int bonefingerTexture1;
    int bonefingerTexture2;
    int bonefingerTexture3;
    int bonefingerId;
    public Block blockbonefinger;
    int boneseedTexture;
    int boneseedId;
    public Item itemboneseed;
    int lichenBlockTexture;
    int lichenId;
    public Block blocklichen;
    int lichenItemTexture;
    int lichenItemId;
    public Item itemlichen;
    int roastedLichenTexture;
    int roastedLichenId;
    public Item itemroastedlichen;
    int creeparaTBTexture;
    int creeparaSideTexture;
    int creeparaId;
    public Block blockcreepara;
    int pricklyPearTexture;
    int pricklyPearId;
    public Block blockpricklypear;
    int fireflowerTexture;
    int fireflowerId;
    public Block blockfireflower;
    int fireLauncherTexture;
    int fireLauncherId;
    public Item itemfirelauncher;
    int dawnflowerTexture;
    int dawnflowerId;
    public Block blockdawnflower;
    int berryBushTexture;
    int berryBushId;
    public Block blockberrybush;
    int berryTexture;
    int berryId;
    public Item itemberry;
    int berryPieTexture1;
    int berryPieTexture2;
    int berryPieTexture3;
    int berryPieId;
    public Item itemberrypie;
    int lotusTexture;
    int lotusId;
    public Block blocklotus;
    int lotusBlossomTexture;
    int lotusBlossomId;
    public Item itemlotusblossom;
    int lilyTexture;
    int lilyId;
    public Block blocklily;
    int lilySeedsTexture;
    int lilySeedsId;
    public Item itemlilyseeds;
    int gildedlilyTexture;
    int gildedlilyId;
    public Block blockgildedlily;
    int smallGildedlilyTexture;
    int smallGildedlilyId;
    public Block blocksmallgildedlily;
    int gildedlilySeedsTexture;
    int gildedlilySeedsId;
    public Item itemgildedlilyseeds;
    int frozenNetherrackTexture;
    int frozenNetherrackId;
    public Block blockfrozennetherrack;
    int chillspikeTexture;
    int chillspikeId;
    public Block blockchillspike;
    int goldenShearsTexture;
    int goldenShearsId;
    public Item itemgoldenshears;
    int autocraftingShearsTexture;
    int autocraftingShearsId;
    public Item itemautocraftingshears;
    int bountyShearsTexture;
    int bountyShearsId;
    public Item itembountyshears;
}
